# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exemple.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexemple.proto\" \n\x0ePersonResponce\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1c\n\rPresonRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\x32>\n\x0bTestService\x12/\n\nTestMethod\x12\x0e.PresonRequest\x1a\x0f.PersonResponce0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exemple_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONRESPONCE']._serialized_start=17
  _globals['_PERSONRESPONCE']._serialized_end=49
  _globals['_PRESONREQUEST']._serialized_start=51
  _globals['_PRESONREQUEST']._serialized_end=79
  _globals['_TESTSERVICE']._serialized_start=81
  _globals['_TESTSERVICE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
